// This file was autogenerated by calcdeps.py
goog.addDependency("../../../../src/calculated_deps.js", [], []);
goog.addDependency("../../../../src/Freebase.deps.js", [], ['goog.events.EventTarget', 'goog.events.EventType', 'goog.ui.CustomButton', 'goog.ui.CustomButtonRenderer', 'goog.ui.Tab']);
goog.addDependency("../../../../src/Freebase.js", ['com.qwirx.freebase'], ['com.qwirx.freebase.DocumentEditor', 'goog.events.EventTarget', 'goog.ui.TabBar', 'goog.ui.Textarea', 'goog.ui.TextareaRenderer', 'goog.ui.SplitPane', 'goog.ui.tree.TreeControl']);
goog.addDependency("../../../../src/Index.js", [], []);
goog.addDependency("../../../../src/documenteditor.js", ['com.qwirx.freebase.CloseButton', 'com.qwirx.freebase.ClosableTab', 'com.qwirx.freebase.Grid', 'com.qwirx.freebase.DocumentEditor'], ['goog.ui.Control', 'goog.ui.CustomButton']);
